version: '3.8'

services:
  hetic-stream:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ApiBaseUrl=https://api.heticstream.com
      - ApiEnabled=true
      - EndpointLogin=/auth/login
      - EndpointRegister=/auth/register
      - EndpointChannels=/channels
      - EndpointMessages=/messages
      - ImageAssetsPath=Assets/Images
      - LightThemeEnabled=false
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - hetic-stream
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"